---
- hosts: nfs-server
  become: yes
  gather_facts: false
  vars_files:
  - ../vars/env_nfs.yml
  tasks:
#Instalamos el nfs-utils en el nodo nfs        
    - name: install nfs-utils
      yum: name=nfs-utils state=latest
# Creamos un directorio para exportar el NFS
    - name: Create a mountable directory if it does not exist
      file:
        path: /nfs-server/
        state: directory
        owner: root
        group: root
        mode: '0775'
# Copiamos el template en el exports file del NFS
    - name: Copy exports file.
      template:
        src: ../j2/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
#Habilitamos los puertos indicados en el archivo env
    - name: Allow Network Ports in Firewalld for nfs
      firewalld:
       port: "{{ item }}"
       state: enabled
       permanent: yes
      with_items: "{{ nfs_ports  }}"
# Permitimos el trafico para los servicios de NFS    
    - name: Permit traffic in default zone for NFS services
      firewalld:
       service: "{{ item }}"
       permanent: yes
       state: enabled
      with_items: "{{ nfs_fw_services }}"

#Iniciamos y habilitamos los servicios indicados en el archivo env
    - name: Starting and Enabling the required services
      service:
       name: "{{ item }}"
       enabled: yes
       state: started
      with_items: "{{ services }}"
