---
- hosts: kubernetes-workers
  become: yes
  gather_facts: false
  vars_files:
  - ../vars/env_variables.yml
  # Autorizamos al usuario root acceder al cluster
  tasks:
#  - name: Copying required files
#    shell: |
#     mkdir -p $HOME/.kube
#     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
#     sudo chown $(id -u):$(id -g) $HOME/.kube/config
    #Copiamos el archivo token en los nodos worker
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token
    #Añadimos los worker  al cluster
  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat join_token | tail -2 > token.sh
     sh token.sh

