---
- hosts: kubernetes
  become: yes
  gather_facts: false
  vars_files:
  - ../vars/env_variables.yml
  tasks:
# Copiamos el repo de k8s en los nodos
  - name: Copy Kubernetes repo file to nodes.
    template:
      src: ../j2/repos/kubernetes.repo.j2
      dest: /etc/yum.repos.d/Kubernetes.repo
      owner: root
      group: root
      mode: 0644
# Copiamos el repo de docker en los nodos
  - name: Copy Docker repo file to nodes.
    template:
      src: ../j2/repos/docker-ce.repo.j2
      dest: /etc/yum.repos.d/Docker-ce.repo
      owner: root
      group: root
      mode: 0644

#Instalamos los paquetes de kubernetes
  - name: Installing packages
    yum:
     name: "{{ packages }}"
     state: present
#Iniciamos los servicios necesarios
  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"
#Habilitamos los puertos necesarios para el cluster
  - name: Allow Network Ports in Firewalld
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ master_ports if ('kubernetes-master' in group_names) else worker_ports }}"

#  - name: Allow workers IPs in Firewalld
#    firewalld:
#      permanent: yes
#      immediate: yes
#      rich_rule: "{{ item }}"
#      state: enabled
#    with_items: "{{ ip_rich_rule if ('kubernetes-master' in group_names)}}"

