api:Version: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cluster-ingress
spec:
  rules:
  - host: 10.0.1.10
    http:
	  paths:
	  - path: /
	    backend:
		  serviceName: nextcloud-server
		  servicePort: 80