#Conjunto de playbooks que desplegan el nodo master
---
- import_playbook: playbooks/common/update_etc_hosts.yml
- import_playbook: playbooks/kubernetes/setting_up_nodes.yml
- import_playbook: playbooks/kubernetes/configure_master_node.yml
